### ISSUE TITLE
Which  built library should Replace the filename in src/mapping.py with ?

### ISSUE THREAD

**Issue by SSZ1** [SYSU-STAR/H2-Mapping#22]
Hi I wanna know which library of tiny-cuda-nn should I use to replace the line of torch.classes.load_library("third_party/sparse_octree/build/lib.xxx/svo.xxx.so")?

![image](https://github.com/SYSU-STAR/H2-Mapping/assets/36888758/2d179918-c74c-4604-95a9-8eaff72dc263)

Is the libtiny-cuda-nn.a that I sohuld replace with?

Thanks a lot for your attention!

**Comment by JIANG-CX** [comment]
Hi, the line of torch.classes.load_library("third_party/sparse_octree/build/lib.xxx/svo.xxx.so") is related to the sparse_octree package located in the third_party folder, rather than tinycudann. For tinycudann, please refer to 'installation 4' in the README for the appropriate instructions. Happy Winter Solstice！Thanks.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: SHANGZHE SUN ***@***.***>
发送时间: Friday, December 22, 2023 11:21:23 AM
收件人: SYSU-STAR/H2-Mapping ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SYSU-STAR/H2-Mapping] Which built library should Replace the filename in src/mapping.py with ? (Issue #22)


Hi I wanna know which library of tiny-cuda-nn should I use to replace the line of torch.classes.load_library("third_party/sparse_octree/build/lib.xxx/svo.xxx.so")?

image.png (view on web)<https://github.com/SYSU-STAR/H2-Mapping/assets/36888758/2d179918-c74c-4604-95a9-8eaff72dc263>

Is the libtiny-cuda-nn.a that I sohuld replace with?

Thanks a lot for your attention!

―

**Comment by SSZ1** [comment]
Thanks a lot!
