### ISSUE TITLE
Can xyz in the world coordinate system achieve the effect of the paper without normalization?

### ISSUE THREAD

**Issue by ZZy129326999** [SYSU-STAR/H2-Mapping#3]
Hello, can xyz in the world coordinate system achieve the effect of the paper without normalization?

**Comment by JIANG-CX** [comment]
Hi, because when using tinycudann, coordinates need to be transformed to the range of 0-1, so when using it, you can give a larger range and then transform the coordinates to the range of 0-1. However, if the range is too much larger than the scene you want to reconstruct, the performance may degrade. Thanks,

**Comment by ZZy129326999** [comment]
> 
Ok, thank you very much!!!!!!!
