### ISSUE TITLE
Hello, When H3-Mapping code release? with Such expectations

### ISSUE THREAD

**Issue by shuttworth** [SYSU-STAR/H2-Mapping#32]
H3-Mapping: Quasi-Heterogeneous Feature Grids for Real-time Dense Explicit Octree SDF Priors Mapping Using Hierarchical Hybrid Representation

**Comment by shuttworth** [comment]
H3-Mapping: Quasi-Heterogeneous Feature Grids for Real-time Dense Explicit Octree SDF Priors Mapping Using Hierarchical Hybrid Representation

**Comment by JIANG-CX** [comment]
Thank you for your attention. Since the paper is currently under review, the code will be released once the paper is accepted.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: shuttworth ***@***.***>
发送时间: Wednesday, May 29, 2024 11:11:02 AM
收件人: SYSU-STAR/H2-Mapping ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SYSU-STAR/H2-Mapping] Hello, When H3-Mapping code release? with Such expectations (Issue #32)


―
